# Generated by Django 5.0.7 on 2024-07-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='joinDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
