# Generated by Django 5.0.7 on 2024-07-20 01:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_userprofile_friends_alter_userprofile_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userID',
            field=models.CharField(default=uuid.UUID('26b61e7c-791e-4dca-9fb9-f75bb12d19af'), max_length=255, unique=True),
        ),
    ]
